In [7]:
class Student:   #OOP
    def info(self,para1):
        print("info, the class I defined")#function body
    def calc(self,param1,param2): 
        return param1+param2
Jim =  Student() 
Jim.info("hello")  #call the function
Jim.calc(3,4)

info, the class I defined


7

In [27]:
class People(object):
   def __init__(self):
       print("__init__")
   def __new__(cls, *args, **kwargs):   #__ new__ () usually returns an instance of this class,   change name to new1 
       print("__new__")
       return object.__new__(cls, *args, **kwargs)
Jim = People()


__new__
__init__


In [34]:
#Write a Student Class that requires counter attribute . It can count the total number of students instantiated
class Student:
    count = 0  #class /instance
    @classmethod
    def __init__(cls):
             cls.count +=1  #
Jim = Student()     #instantiated
Kate= Student()     #instantiated
Join= Student()     #instantiated
print(Student.count)

3


In [36]:
class Student:
    counter = 0
    
    def __init__(self, x = 1):
        Student.counter += x
    
Jim = Student()
Jack = Student()
Mimi = Student()
Mimi1 = Student()
Student.counter


4

In [48]:
class Demo_property:  
    class_name = "Demo_property_name" 
    def __init__(self,x = 0):
        self.x = x   
        print("----------%s"%self.x)
    def info(self):
        print("info, the class I defined")
    def change1(self,x):
        self.x = x   
        print(self.x)
    @classmethod  #annotation, we can use cls to call the properities, methods
    def chang2(cls,y): 
        print("----------------") 
    @staticmethod #
    def change3():
        print("change3 is static method %s")
dpa = Demo_property()
dpa.chang2('hello')
Demo_property.chang2('hello')
Demo_property.change3()

----------0
----------------
----------------
change3 is static method %s


In [69]:
class Dog:
    def __init__(self,x=0,y=0,color='yellow'):
        self.x = x
        self.y = y
        self.color = color
        print("the color is %s"%self.color)
    def crawl(self,x,y):
        self.x = x
        self.y = y
        print("The current position is:(%d, %d),and the color is"%(self.x,self.y))
    def attack(self):
        print('use teetch')
class Haski(Dog):  
    def attack(self):  #
        print('use teetch and simle')
haski = Haski(color='white')  #color='white'
haski.crawl(3,2)
haski.attack()

the color is white
The current position is:(3, 2),and the color is
use teetch and simle


In [70]:
class Parent(object):
    x = 3  #class properity
class Child1(Parent):  #Subclass
    pass  
class Child2(Parent):  #Subclass
    pass
print(Parent.x, Child1.x, Child2.x) 
Child1.x = 2
print(Parent.x, Child1.x =2, Child2.x) #Child1.x =2
Parent.x = 3
print(Parent.x, Child1.x, Child2.x)

1 1 1
1 2 1
3 2 3


In [71]:
#!/usr/bin/env python
# coding: utf-8

import numpy as np
from PIL import Image

if __name__ == '__main__':
    image_file = '3.jpg'
    height = 100#change image height to 100

    img = Image.open(image_file)
    img_width, img_height = img.size
    width = 2 * height * img_width // img_height    
    img = img.resize((width, height), Image.ANTIALIAS)#change image size
    pixels = np.array(img.convert('L')) 
    print(pixels.shape)
    print(pixels)
    chars = "MNHQ$OC?7>!:-;. " #256 color,M means 0-15，N means 16-31
    N = len(chars)
    step = 256 // N
    print(N)
    result = ''
    for i in range(height):
        for j in range(width):
            result += chars[pixels[i][j] // step]                          
        result += '\n'
    with open('text.txt', mode='w') as f:
        f.write(result)

(100, 200)
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
16
